name: Java CI with my tests

on:
  workflow_dispatch:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  TEST_URL: ${{ vars.TEST_URL }}
  TEST_PASSWORD: ${{ vars.TEST_PASSWORD }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 19.0.2
        uses: actions/setup-java@v3
        with:
          java-version: '19.0.2'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn -B package --file pom.xml
